version: "3.9"
services:
  redis:
    image: redis:alpine
    volumes:
      - ./data/redis/:/data
    ports:
      - 6379:6379

  new-newt-crawler:
    build:
      context: ./
      dockerfile: Dockerfile
    command: crawler
    env_file:
      - ./.env
    depends_on:
      - redis

  new-newt-web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: web
    env_file:
      - ./.env
    depends_on:
      - redis
